### ISSUE TITLE
Fix tests for micronaut-oracle-autonomous-db guide

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1038]
I had to skip the tests for the `micronaut-oracle-autonomous-db` guide. They seem to get stacked. 

https://github.com/micronaut-projects/micronaut-guides/commit/a2de3509140e80f65160e29f88f654b97a5b81cc

**Comment by sdelamo** [comment]
@shingjo is this something you could investigate?

**Comment by melix** [comment]
Running the test shows:

> Loaded 1 test resources resolvers: io.micronaut.testresources.testcontainers.GenericTestContainerProvider

Which indicates that there's no particular support for Oracle Autonomous Database loaded (I'm not surprised, since I didn't implement anything specific to it).
