### ISSUE TITLE
@features@ and @features-words@ macros not working

### ISSUE THREAD

**Issue by burtbeckwith** [micronaut-projects/micronaut-guides#1073]
This seems to affect all or most of the guides - `@features@` and `@features-words@` aren't expanded, so create commands look like

```
mn create-app example.micronaut.micronautguide \
    --features=@features@ \
    --build=gradle --lang=java
```
and the launch instructions look like

`If you use Micronaut Launch, select Micronaut Application as application type and add @features-words@ features.`

**Comment by burtbeckwith** [comment]
When I build locally it works fine

**Comment by alvarosanchez** [comment]
I think #1070 broke it /cc @timyates

**Comment by timyates** [comment]
Fix pushed...  Sorry about that

**Comment by alvarosanchez** [comment]
Thanks!
