### ISSUE TITLE
Make test action stable

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1163]
https://github.com/micronaut-projects/micronaut-guides/actions/workflows/snapshot.yml

if we need to run only 17, I am fine with it.

**Comment by timyates** [comment]
It's both 17 and 11 that seem to have random failures...  Investigating...

**Comment by timyates** [comment]
This will help, and should fix most of the issues

https://github.com/micronaut-projects/micronaut-guides/pull/1164/files

I don't know why that was sometimes passing with one JDK 🤔
