### ISSUE TITLE
Kotlin version of Custom Validation annotation guide

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1246]
https://guides.micronaut.io/latest/micronaut-custom-validation-annotation.html

**Comment by codewithbear** [comment]
I just proposed a kotlin version for this guide https://guides.micronaut.io/latest/micronaut-scope-types.html
https://github.com/micronaut-projects/micronaut-guides/pull/1339

Can try and fix this one as well 😄
