### ISSUE TITLE
No links for the Oracle Autonomous Database guide

### ISSUE THREAD

**Issue by burtbeckwith** [micronaut-projects/micronaut-guides#1462]
https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db.html doesn't have the expected links, just the language icons

**Comment by sdelamo** [comment]
@timyates can you investigate this? Maybe we broke it with the `skips` functionality https://github.com/micronaut-projects/micronaut-guides/commit/52d8ccce941f2ef428a2a6cf083ec61e5aa09c8d
