### ISSUE TITLE
Move skip logic to guides core

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1503]
https://github.com/micronaut-projects/micronaut-guides/blob/master/buildSrc/src/main/groovy/io/micronaut/guides/GuideMetadata.groovy#L80-L110

**Comment by AndreaLaGrotteria** [comment]
Does it make sense to still have the Skip object? As far as I can see, it is a field that a guide could have in its metadata.json. But none of the current guides has it
