### ISSUE TITLE
Add rocker macro to core

### ISSUE THREAD

**Issue by AndreaLaGrotteria** [micronaut-projects/micronaut-guides#1537]
Move https://github.com/micronaut-projects/micronaut-guides/blob/bbcc6cd06a38bf3f03dbd38abb78db50230c55ce/buildSrc/src/main/groovy/io/micronaut/guides/GuideAsciidocGenerator.groovy#L152 to core

**Comment by sdelamo** [comment]
I don't understand what this means.

**Comment by sdelamo** [comment]
> for this [https://github.com/micronaut-projects/micronaut-guides/blob/bbcc6cd06a38bf3f03dbd3[…]c/main/groovy/io/micronaut/guides/GuideAsciidocGenerator.groovy](https://github.com/micronaut-projects/micronaut-guides/blob/bbcc6cd06a38bf3f03dbd38abb78db50230c55ce/buildSrc/src/main/groovy/io/micronaut/guides/GuideAsciidocGenerator.groovy#L152)

I wont' give priority to this. There is only one occurrence. Not sure what it really does.
