### ISSUE TITLE
Review Creating your first Micronaut app

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#16]

**Comment by gijsleussink** [comment]
While reviewing [the Maven/Java guide](https://guides.micronaut.io/latest/creating-your-first-micronaut-app-maven-java.html), I noticed the steps to generate a native image with GraalVM include an example of installing 21.2.0.r8 (`sdk install java 21.2.0.r8-grl`), but Java 8 support isn't provided (through SDKMan) anymore.

Reviewing done ✅

**Comment by burtbeckwith** [comment]
When 21.2 was first released only v11 was supported by SDKMan, but they added v8 and v16. This is the GraalVM output I get when I run `sdk list java`:

```
 GraalVM       |     | 21.2.0.r16   | grl     |            | 21.2.0.r16-grl
               |     | 21.2.0.r11   | grl     | installed  | 21.2.0.r11-grl
               |     | 21.2.0.r8    | grl     |            | 21.2.0.r8-grl
               |     | 21.1.0.r11   | grl     | local only | 21.1.0.r11-grl
               |     | 21.1.0.r8    | grl     | installed  | 21.1.0.r8-grl
               |     | 20.3.3.r11   | grl     |            | 20.3.3.r11-grl
               |     | 20.3.3.r8    | grl     |            | 20.3.3.r8-grl
               |     | 20.3.2.r8    | grl     |            | 20.3.2.r8-grl
               |     | 19.3.6.r11   | grl     |            | 19.3.6.r11-grl
               |     | 19.3.6.r8    | grl     |            | 19.3.6.r8-grl
```

**Comment by ilopmar** [comment]
Exactly what Burt said. They first released GraalVM for JDK11 on July 20th (as scheduled) and a week later they released it for JDK 8 and 16.

**Comment by gijsleussink** [comment]
Thanks for the feedback @burtbeckwith 
Funny, I only see
```
 GraalVM       |     | 21.2.0.r16   | grl     |            | 21.2.0.r16-grl
               |     | 21.2.0.r11   | grl     |            | 21.2.0.r11-grl
               |     | 21.1.0.r16   | grl     | local only | 21.1.0.r16-grl
               |     | 21.0.0.r11   | grl     | local only | 21.0.0.r11-grl
               |     | 20.3.3.r11   | grl     |            | 20.3.3.r11-grl
               |     | 20.1.0.r11   | grl     | local only | 20.1.0.r11-grl
               |     | 19.3.6.r11   | grl     |            | 19.3.6.r11-grl
```

**Comment by burtbeckwith** [comment]
@gijsleussink try running `sdk update`

**Comment by burtbeckwith** [comment]
I see what's happening - there's no 21.2.0 for JDK 8 on Mac, see https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0
Ivan and I use Linux, so it shows up for us

**Comment by ilopmar** [comment]
:penguin: FTW!
