### ISSUE TITLE
Make the Guide content area wider

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#248]
I think we should make the guide area wider. 

<img width="1200" alt="Screenshot 2021-05-19 at 07 52 24" src="https://user-images.githubusercontent.com/864788/118762878-400aca00-b877-11eb-9561-d7eef5c4fe5a.png">

**Comment by jeffscottbrown** [comment]
This may be fixed already.

![Screenshot 2023-12-13 at 12 28 52 PM](https://github.com/micronaut-projects/micronaut-guides/assets/15482/d38eb231-1964-4faf-8e60-e2d5e8031d3f)

**Comment by wetted** [comment]
The guides look fine in Chrome, Safari, Firefox.
