### ISSUE TITLE
Problem With Guide Zip Files

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-guides#395]
The zip file at https://guides.micronaut.io/latest/micronaut-jpa-hibernate-maven-java.zip is linked from https://guides.micronaut.io/latest/micronaut-jpa-hibernate-maven-java.html.  When I download that zip file on a Windows machine I see that if I right click and select “Extract All…” Windows shows an error message indicating the zip is invalid.  If I double click the zip to open it up in Explorer, it appears to open and appears to be empty.  The exact same file on the same machine does extract successfully using 7-Zip.

I have not verified that this is the issue but I suspect that the leading slash in the entry paths may be causing a problem.

I only tested the Guide linked above, but I suspect the problem is the same in other guides.

**Comment by graemerocher** [comment]
FWIW people at Oracle have hit this too

**Comment by sdelamo** [comment]
@micronaut-projects/core-developers if anyone works with Windows it would be great if you could check this issue.

**Comment by jeffscottbrown** [comment]
> if anyone works with Windows it would be great if you could check this issue

@sdelamo Is there something you would like me to check beyond what is described in the original question?

**Comment by sdelamo** [comment]
> > if anyone works with Windows it would be great if you could check this issue
> 
> @sdelamo Is there something you would like me to check beyond what is described in the original question?

No.

Please note that I don't have access to any windows Machine.
