### ISSUE TITLE
micronaut-data-jdbc-repository failed test cause of not working Id generation

### ISSUE THREAD

**Issue by cmincu** [micronaut-projects/micronaut-guides#530]
@GeneratedValue(GeneratedValue.Type.AUTO) not works as expected and testGenreCrudOperations fails with error: 
`Null argument specified for [id].`

Also update as `genreRepository.update(command.getId(), command.getName());` not working as expected an entity not part of it.

Using:
Java 11
Micronaut 3.0.1

**Comment by sdelamo** [comment]
I believe this is fixed in the latest version of the guide.
