### ISSUE TITLE
Review @Configuration and @ConfigurationBuilder

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#54]

**Comment by gijsleussink** [comment]
Starting a review

**Comment by gijsleussink** [comment]
Reviewing of the [Maven/Java guide](https://guides.micronaut.io/latest/micronaut-configuration-maven-java.html) done ✅

**Comment by gijsleussink** [comment]
Small typo in section 5.1: It says `application.xml` instead of `application.yml`.

**Comment by ilopmar** [comment]
> Small typo in section 5.1: It says `application.xml` instead of `application.yml`.

Can you please submit a PR: https://github.com/micronaut-projects/micronaut-guides/blob/master/guides/micronaut-configuration/micronaut-configuration.adoc

**Comment by ilopmar** [comment]
I've fixed that in #524
