### ISSUE TITLE
Update oracle cloud guide

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-guides#613]
From @pgressa : We need to update the guide https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html which uses mn create-app --features=oracle,oracle-cloud-atp,data-jdbc,oracle-cloud-sdk,flyway,testcontainers example.micronaut.micronautguide --build=gradle --lang=java --jdk=11 to generate template, and it will fail since oracle and oracle-cloud-atp will be both db feature. Also we can remove oracle-cloud-sdk.

**Comment by sdelamo** [comment]
@pgressa which features should the guide have? 

Can you please create a pr which upgrades the guide. 

`./gradlew -Dmicronaut.guide=micronaut-oracle-autonomous-db` build will build the guide locally. 

You will need to update the guide `guides/micronaut-oracle-autonomous-db/metadata.json` and maybe the copy.

**Comment by graemerocher** [comment]
@burtbeckwith wrote this guide and is better placed to make the change

**Comment by sdelamo** [comment]
I had to add manually test containers for `oracle-xe`

https://github.com/micronaut-projects/micronaut-guides/pull/622/commits/1a6513ce4d44eaf03618640e45707e4c6b4a0161
