### ISSUE TITLE
Cache Guide doesn't mention that class needs to be Serializable

### ISSUE THREAD

**Issue by jacekgajek** [micronaut-projects/micronaut-guides#666]

**Comment by sdelamo** [comment]
How can I verify this? I don't think it needed to be Serializable when we wrote the guide

**Comment by jacekgajek** [comment]
https://github.com/jacekgajek/redis-error-demo
This is actually a showcase for a bug in caching suspending funs, but if you remove `Serializable` then the non-suspending controllers will fail with error
```
 "message": "Internal Server Error: I/O error occurred during serialization: com.example.BarController$Bar"
```

**Comment by sdelamo** [comment]
> https://github.com/jacekgajek/redis-error-demo This is actually a showcase for a bug in caching suspending funs, but if you remove `Serializable` then the non-suspending controllers will fail with error
> 
> ```
>  "message": "Internal Server Error: I/O error occurred during serialization: com.example.BarController$Bar"
> ```

Can you create an issue in cache repository pointing to your repo and providing as much information as possible. If I understand you correctly, you found a bug for Micronaut Kotlin apps and Cache.
