### ISSUE TITLE
run guide tests gradle task should be disabled if the guide does not support the JDK version being used

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#850]
For example, if you use JDK 11 the gradle task to execute the tests of the guide `micronaut-java-records` which is only JDK 17 should not be enabled.

**Comment by timyates** [comment]
All the guides are created with

```
java {
    sourceCompatibility = JavaVersion.toVersion("11")
    targetCompatibility = JavaVersion.toVersion("11")
}
```

So will never run on Java 8 🤔

**Comment by sdelamo** [comment]
don't we create them with the JDK being used?

**Comment by timyates** [comment]
This is getting done in https://github.com/micronaut-projects/micronaut-guides/pull/852 as well as the connection to Gradle Enterprise

**Comment by timyates** [comment]
Fixed in #852

**Comment by timyates** [comment]
> don't we create them with the JDK being used?

It doesn't look to be that way...  I guess they should be?  They seems to come in as 11 all the time even if I'm on JDK 8 🤔

That's why I originally did the TODO guide as Java 11 https://github.com/micronaut-projects/micronaut-guides/pull/822#discussion_r824329890

**Comment by sdelamo** [comment]
For each guide we ship a ZIP file wit the complete solution. The idea is that the ZIP is JDK 11 but if you have a minimum requirement of 17 it should be 17.

**Comment by sdelamo** [comment]
Java records already is generated with 17 https://guides.micronaut.io/latest/micronaut-java-records-gradle-java.html see ZIP file there.

**Comment by timyates** [comment]
Cool, so we cannot run the tests on Java 8

**Comment by timyates** [comment]
I'll close this then
