### ISSUE TITLE
Project should publish to Gradle Enterprise

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-guides#851]
We should be publishing runs to Gradle Enterprise, but we do not wish to add our full build plugin

**Comment by sdelamo** [comment]
We have these secrets available: 

- `GRADLE_ENTERPRISE_ACCESS_KEY`

- `GRADLE_ENTERPRISE_CACHE_PASSWORD`

- `GRADLE_ENTERPRISE_CACHE_USERNAME`

we will need to add it to github actions https://github.com/micronaut-projects/micronaut-security/blob/master/.github/workflows/gradle.yml#L45-L47

**Comment by sdelamo** [comment]
@timyates work on the branch of this PR https://github.com/micronaut-projects/micronaut-guides/pull/852/

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-guides/pull/852
