### ISSUE TITLE
Improvements to Mybatis guides

### ISSUE THREAD

**Issue by leadtrip** [micronaut-projects/micronaut-guides#873]
The Maven and Gradle guides for groovy and kotlin in section '4.x MyBatis configuration' contain the text 
'Create the following @Factory class in src/main/**java/example/micronaut/MybatisFactory.java**:'

On the following line the correct path and suffix for the respective language is specified for MybatisFactory, assuming the relevant line in /guides/micronaut-data-access-mybatis/micronaut-data-access-mybatis.adoc requires removal/updating.

Also, all of the guides (including Java) in the following section '4.x Domain' state 'Create the domain entities:' but only the Genre entity is shown & not the Book entity so you need to download the zip to complete the guide.

https://guides.micronaut.io/latest/micronaut-data-access-mybatis.html

**Comment by hollingsworthd** [comment]
Good catches, thank you, @leadtrip!
