### ISSUE TITLE
Investigate why maven Tests were failing in CI

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#917]
@burtbeckwith had to comment out maven tests for multiple guides here: 

https://github.com/micronaut-projects/micronaut-guides/pull/910/commits/6655240c2e1b88ceb12885d07aa6425f949d9aa6

- [ ] `micronaut-security-x509`
- [ ] `micronaut-security-session`
- [ ] `micronaut-security-keys-jwks`
- [ ] `micronaut-security-jwt`
- [ ] `micronaut-security-jwt-cookie`
- [ ]  `micronaut-oauth2-linkedin`  
- [ ]  `micronaut-liquibase` 
- [ ] `micronaut-graphql-todo`
- [ ] `micronaut-data-jdbc-repository`
- [ ] `micronaut-cloud-oidc-oracle`
- [ ] `micronaut-cloud-oidc-base`

We need to investigate why they fail.

**Comment by timyates** [comment]
All of these passed in https://github.com/micronaut-projects/micronaut-guides/pull/919 on a snapshot of 3.4.4 containing https://github.com/micronaut-projects/micronaut-starter/pull/1208

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-starter/pull/1208 and https://github.com/micronaut-projects/micronaut-guides/pull/919
