### ISSUE TITLE
Investigate failure with secrets manager guide 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#918]
- [ ] `micronaut-aws-secretsmanager`

@burtbeckwith disabled them here because they were failing: 

https://github.com/micronaut-projects/micronaut-guides/pull/910/commits/718f52cc0d268afcc57d3e552e25e10d21b99013

**Comment by timyates** [comment]
Locally, this requires env vars

It passed on Java 17 here
But failed on Java 11 [see](https://github.com/micronaut-projects/micronaut-guides/runs/6310866625?check_suite_focus=true#step:5:290) [build-scan](https://ge.micronaut.io/s/54evmswyjdzoi/console-log?task=:micronautAwsSecretsmanagerRunTestScript)

```
java.lang.NoSuchMethodError: 'boolean io.micronaut.inject.ast.ElementQuery$Result.isIncludeEnumConstants()'
```

Have we changed the Kapt processor?  Is maven using the wrong version?

This is the change

https://github.com/micronaut-projects/micronaut-core/commit/c2573edc30f6ca53308d57d16804594e00795a3a#diff-4b79a747fdafcdfd7bd479abcfcf87be69da19f580c1d0896338c421f2215421L142-L145

Something must be out of step...

I suspect this is the same issue for https://github.com/micronaut-projects/micronaut-guides/issues/917 too

**Comment by timyates** [comment]
Paging @dstepanov incase they can think of something

**Comment by sdelamo** [comment]
@alvarosanchez any idea?

**Comment by alvarosanchez** [comment]
This must be because there are multiple copies of `micronaut-inject` in the compilation classpath

**Comment by timyates** [comment]
This is a failing scan if it helps https://ge.micronaut.io/s/jho7s7she5cj6

**Comment by timyates** [comment]
Don't think it does though, as I can't find kapt dependencies

**Comment by timyates** [comment]
Could it be this? https://github.com/micronaut-projects/micronaut-kotlin/pull/400/files

**Comment by timyates** [comment]
Ok, so it works if I move

```
               <annotationProcessorPath>
                 <groupId>io.micronaut</groupId>
                 <artifactId>micronaut-inject-java</artifactId>
                 <version>${micronaut.version}</version>
               </annotationProcessorPath>
```

above

```
               <annotationProcessorPath>
                 <groupId>io.micronaut.security</groupId>
                 <artifactId>micronaut-security-annotations</artifactId>
                 <version>${micronaut.security.version}</version>
               </annotationProcessorPath>
```

---

### Unrelated

as an aside, we seem to get 

```
               <annotationProcessorPath>
                 <groupId>io.micronaut</groupId>
                 <artifactId>micronaut-graal</artifactId>
                 <version>${micronaut.version}</version>
               </annotationProcessorPath>
```

three times in the generated pom 🤔

**Comment by timyates** [comment]
Security annotations pull in 

```
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject</artifactId>
      <version>3.3.4</version>
      <scope>compile</scope>
    </dependency>
```

https://search.maven.org/artifact/io.micronaut.security/micronaut-security-annotations/3.5.0/jar

**Comment by alvarosanchez** [comment]
> three times in the generated pom

The 3 of them are wrong. That dependency is added automatically via a profile from the parent POM: https://search.maven.org/artifact/io.micronaut/micronaut-parent/3.4.3/pom

**Comment by timyates** [comment]
So how do we solve this?

As far as I can see, we have a few options:

1. Change the order of the Kapt dependencies in the generated POM to have inject first
2. Re-introduce that renamed method in https://github.com/micronaut-projects/micronaut-core/commit/c2573edc30f6ca53308d57d16804594e00795a3a#diff-4b79a747fdafcdfd7bd479abcfcf87be69da19f580c1d0896338c421f2215421L142-L145 and delegate to the new method
3. Something else...

I think all of the above would require a 3.4.4?

**Comment by alvarosanchez** [comment]
I guess the only valid choice is option 1

**Comment by timyates** [comment]
Pushed [the above](https://github.com/micronaut-projects/micronaut-starter/pull/1208) as a draft...  My confidence is low 🤔

**Comment by timyates** [comment]
This passed in https://github.com/micronaut-projects/micronaut-guides/pull/919 on a snapshot of 3.4.4 containing https://github.com/micronaut-projects/micronaut-starter/pull/1208

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-starter/pull/1208 and https://github.com/micronaut-projects/micronaut-guides/pull/919
